#Wiremission##
services:
  wiremission:
    image: lscr.io/linuxserver/wireguard:1.0.20210914
    container_name: wiremission
    healthcheck:
      test: ["CMD", "curl", "-s", "--max-time", "5", "https://ipinfo.io/ip"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    ports:
      - "127.0.0.1:8060:6767/tcp" # Bazarr
      - "127.0.0.1:8020:7878/tcp" # Radarr
      - "127.0.0.1:8010:8989/tcp" # Sonarr
      - "127.0.0.1:8050:9091/tcp" # Transmission
      - "127.0.0.1:8040:9696/tcp" # Prowlarr
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
      - SYS_MODULE #optional
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - ${WM_VPN_CONF}:/config/wg_confs/wg0.conf
      - ./config/:/config
      - /lib/modules:/lib/modules #optional
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
