services:
  teamspeak:
    image: teamspeak
    container_name: teamspeak
    restart: unless-stopped
    ports:
      - "9987:9987/udp" #VOIP
      - "10011:10011"   #ServerQuery (admin-cli)
      - "30033:30033"   #File Transfer
    environment:
      TS3SERVER_LICENSE: accept
    volumes:
      - ./volumes/teamspeak-server:/var/ts3server
    networks:
      - apps
