##POSTGRES##
services:
  postgres:
    image: postgres:13.4-alpine
    container_name: postgres_CH
    restart: unless-stopped
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASS}
      - POSTGRES_DB=hedgedoc
    volumes:
      - './Postgres/Volumes:/var/lib/postgresql/data'
    ports:
      - 5432:5432
    networks:
       - apps


