services:
  joplin:
    image: joplin/server:latest
    container_name: joplin
    restart: unless-stopped
    ports:
      - 127.0.0.1:22300:22300
    environment:
      - APP_PORT=22300
      - APP_BASE_URL=https://joplin.${DOMAIN_NAME}
      - DB_CLIENT=pg
      - POSTGRES_HOST=postgres
      - POSTGRES_PORT=${JL_DATABASE_PORT}
      - POSTGRES_DATABASE=${JL_DATABASE_NAME}
      - POSTGRES_USER=${JL_DATABASE_USER}
      - POSTGRES_PASSWORD=${JL_DATABASE_PASS}
    networks:
      - apps
