include:
  # ┌─────────────────────────────────────┐
  # │           ACTIVE SERVICES           │
  # └─────────────────────────────────────┘
  - heimdall/heimdall.yml
  - homeassistant/homeassistant.yml
  - matrix/matrix.yml
  - matrix/bridges/mautrix-telegram/mautrix-telegram.yml
  - matrix/bridges/mautrix-whatsapp/mautrix-whatsapp.yml
  - matrix/bridges/mautrix-signal/mautrix-signal.yml
  - mealie/mealie.yml
  - pi-hole/pi-hole.yml
  - postgres/postgres.yml
  - joplin/joplin.yml
  - postfix/postfix.yml
  - diun/diun.yml
  - fastf1/fastf1.yml
  - teamspeak/teamspeak.yml
  - sonarr/sonarr.yml
  - radarr/radarr.yml
  - jellyfin/jellyfin.yml
  - prowlarr/prowlarr.yml
  - transmission/transmission.yml
  - bazarr/bazarr.yml
  - wiremission/wiremission.yml
  
  # ┌─────────────────────────────────────┐
  # │          DISABLED SERVICES          │
  # └─────────────────────────────────────┘
  # - cadvisor/cadvisor.yml
  # - grafana/grafana.yml
  # - prometheus/prometheus.yml
  # - vaultwarden/vaultwarden.yml
  # - wireguard/wireguard.yml
  # - signal/Signal.yml
  # - hedgedoc/hedgedoc.yml

networks:
  web:
    driver: bridge
  monitoring:
    driver: bridge
  apps:
    driver: bridge
  arrStack:
    driver: bridge
