services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:1.28.2
    container_name: prowlarr
    restart: unless-stopped
    depends_on:
      wiremission:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Paris/Europe
    volumes:
      - './volumes/:/config'
      - ${ARR_DL_DIR}:/downloads
      - ${ARR_MEDIA_DIR}:/media
    network_mode: "service:wiremission"
