services:
# ------------------------
# Synapse
# ------------------------
  synapse:
    image: matrixdotorg/synapse:latest
    container_name: Matrix_CH
    restart: unless-stopped
    ports:
     - 127.0.0.1:6050:8008 #HTTP
     - 127.0.0.1:6051:8448 #Federation
    environment:
     SYNAPSE_SERVER_NAME: https://matrix.${DOMAIN_NAME}
     SYNAPSE_REPORT_STATS: "yes"
     SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
    volumes:
     - ./Volumes:/data
    networks:
     - apps
