FROM alpine:3.21.3


RUN apk update && \
    apk add --no-cache python3 py3-pip pipx openssh openrc && \
    rm -rf /var/cache/apk/*

ENV PYTHONUNBUFFERED=1

RUN pipx install --include-deps ansible
RUN export PATH=$PATH:~/.local/bin

CMD ["sleep", "10000"]
