services:
  jellyfin:
    image: lscr.io/linuxserver/jellyfin:latest
    container_name: jellyfin_CH
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Paris/Europe
      - JELLYFIN_PublishedServerUrl=http://${HOST_URL}
    volumes:
      - ./Config/:/config
      - ${ARR_MEDIA_DIR}:/media
    ports:
      - 8030:8096
      - 8031:8920
      - 8032:7359/udp
      - 8033:1900/udp
    networks:
      - arrStack
