services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission_CH
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Paris/Europe
      - TRANSMISSION_WEB_HOME= #optional
      - USER=${TM_USER} #optional
      - PASS=${TM_PASS} #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /Config/:/config
      - ${ARR_DL_DIR}:/downloads
      - ${ARR_MEDIA_DIR}:/media
    network_mode: "service:wiremission"
