services:
  transmission:
    image: lscr.io/linuxserver/transmission:latest
    container_name: transmission_CH
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Paris/Europe
      - TRANSMISSION_WEB_HOME= #optional
      - USER= #optional
      - PASS= #optional
      - WHITELIST= #optional
      - PEERPORT= #optional
      - HOST_WHITELIST= #optional
    volumes:
      - /Config/:/config
    ports:
      - 8050:9091
      - 8051:51413
      - 8052:51413/udp
    networks:
      - arrStack
