services:
# ------------------------
# Synapse
# ------------------------
  synapse:
    image: matrixdotorg/synapse:v1.150.0
    container_name: matrix
    restart: unless-stopped
    ports:
     - 127.0.0.1:6050:8008 #HTTP
     - 127.0.0.1:6051:8448 #Federation
    environment:
     SYNAPSE_SERVER_NAME: https://matrix.${DOMAIN_NAME}
     SYNAPSE_REPORT_STATS: "yes"
     SYNAPSE_CONFIG_PATH: "/data/homeserver.yaml"
    volumes:
     - ./volumes:/data
    networks:
     - apps
#------------------------
# Synapse-admin
#------------------------
  synapse-admin:
    image: ghcr.io/etkecc/synapse-admin:v0.10.4-etke40
    container_name: synapse-admin
    restart: unless-stopped
    ports:
      - "127.0.0.1:8082:8080"
    depends_on:
      - synapse
    networks:
      - apps

# ------------------------
# Sticker picker
# ------------------------
  stickerpicker:
    image: nginx:1.28-alpine
    container_name: matrix-stickerpicker
    restart: unless-stopped
    ports:
      - "127.0.0.1:8083:80"
    volumes:
      - ./volumes/stickers:/usr/share/nginx/html:ro
      - ./stickers-nginx.conf:/etc/nginx/conf.d/default.conf:ro
    networks:
      - apps
