services:
  include:
  - Cadvisor/Cadvisor.yml
  - Grafana/grafana.yml
  - Hedgedoc/Hedgedoc.yml 
  - Heimdall/Heimdall.yml
  - Mealie/Mealie.yml
  - Pihole/Pihole.yml
  - Portainer/Portainer.yml
  - Postgres/Postres.yml
  - Prometheus/Prometheus.yml
  - Vaultwarden/Vaultwarden.yml
  - Wireguard/Wireguard.yml

##MISC##
networks:
  monitoring:
    driver: bridge
  apps:
    driver: bridge
