FROM alpine:3.21.3

RUN apk update
RUN apk add nginx
RUN mv /etc/nginx/http.d/default.conf /etc/nginx/http.d/default.conf.bak


COPY ./nginx.conf /etc/nginx/http.d/default.conf
COPY ./sites/*.html /var/www/CloudHobo/
COPY ./sites/*.css /var/www/CloudHobo/
