FROM alpine:3.21.3

RUN apk update
RUN apk add nginx
RUN mv /etc/nginx/http.d/default.conf /etc/nginx/http.d/default.conf.bak


COPY ./nginx/nginx.conf /etc/nginx/http.d/default.conf
COPY ./nginx/sites/*.html /var/www/CloudHobo/
COPY ./nginx/sites/*.css /var/www/CloudHobo/
