services:
  nginx:
    build:
      dockerfile: Dockerfile.nginx
    container_name: CHnginx
    entrypoint: nginx -g "daemon off;"
    ports:
      - 8080:8080
    restart: unless-stopped
    network_mode: "host"
