FROM alpine:3.21.3

RUN apk update
RUN apk add nginx
RUN mv /etc/nginx/http.d/default.conf /etc/nginx/http.d/default.conf.bak


COPY ./nginx.conf /etc/nginx/http.d/default.conf
COPY ./*.html /var/www/CloudHobo/
COPY ./*.css /var/www/CloudHobo/
