services:  
  diun:
    image: crazymax/diun:4.31.0
    container_name: diun
    command: serve
    restart: always
    volumes:
      - "./volumes/data:/data"
      - "./volumes/config.yml:/diun.yml:ro"
      - "/var/run/docker.sock:/var/run/docker.sock"
    environment:
      - "TZ=Europe/Paris"
      - "LOG_LEVEL=info"
      - "LOG_JSON=false"
