services:
  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr_CH
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Paris/Europe
    volumes:
      - ./Volumes:/config
      - ${ARR_DL_DIR}:/downloads
      - ${ARR_MEDIA_DIR}:/media
    network_mode: "service:wiremission"
