##PROMETHEUS##
services:
  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus_CH
    restart: unless-stopped
    ports:
      - 7010:9090
    command:
      - --config.file=/etc/prometheus/prometheus.yml
      - --web.config.file=/etc/prometheus/web.yml
    volumes:
      - './Config/prometheus.yml:/etc/prometheus/prometheus.yml'
      - './Config/web.yml:/etc/prometheus/web.yml'
      - '${SSL_CERT_PATH}:/app/ssl/cert.pem'
      - '${SSL_KEY_PATH}:/app/ssl/key.pem'
    depends_on:
      - cadvisor
    networks:
      - monitoring


