services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:1.4.5
    container_name: bazarr
    restart: unless-stopped
    depends_on:
      wiremission:
        condition: service_healthy
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /bazarr/config:/config
      - ${ARR_DL_DIR}:/downloads
      - ${ARR_MEDIA_DIR}:/media
    network_mode: "service:wiremission"
