##HEIMDALL##
services:
  heimdall:
    image: lscr.io/linuxserver/heimdall:latest
    container_name: heimdall_CH
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - './Volumes/Config:/config'
      - '${SSL_CERT_PATH}:/config/keys/cert.pem'
      - '${SSL_KEY_PATH}:/config/keys/key.pem'
    ports:
      - 6050:443
      - 6051:80
    networks:
      - apps


