services:
  bazarr:
    image: lscr.io/linuxserver/bazarr:latest
    container_name: bazarr_CH
    restart: unless-stopped
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Europe/Paris
    volumes:
      - /Bazarr/Config:/config
      - ${ARR_DL_DIR}:/downloads
      - ${ARR_MEDIA_DIR}:/media
    network_mode: "service:wiremission"
